"""
teacher_knowledge_base/context.py — M6.1: TKB build context.

TKBContext is the single shared object passed through every stage of the
TKB build pipeline. It holds:
  - the loaded compiler artifacts (from loaders.py)
  - the TKBMetadata (artifact_id, schema_version, etc.)
  - the partial TKBState (accumulated outputs from completed stages)
  - the pipeline configuration (determinism settings, validation flags)
  - the accumulated diagnostics (warnings, errors, ambiguities)

DESIGN: TKBContext is deliberately NOT a dataclass — it is a mutable
container that builder stages write their outputs into as the pipeline
progresses. Only the final serialization step reads it in full. This
mirrors the BuildExecutor's own ExecutionContext pattern.

DETERMINISM: TKBContext never generates IDs or timestamps itself. All
deterministic IDs are generated by the builders using the UUID5 strategy
in metadata.py. The context only stores what builders give it.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .metadata import TKBMetadata, TKBCompilerInformation

logger = logging.getLogger("teacher_knowledge_base.context")


@dataclass
class TKBDiagnostics:
    """Accumulated diagnostics across all pipeline stages.

    errors: fatal — prevent a valid TKB artifact from being produced.
    warnings: non-fatal — recorded but do not block artifact production.
    ambiguities: architectural ambiguities found during implementation
                 (per M6.1 rule: document, do NOT redesign).
    """
    errors: List[Dict[str, Any]] = field(default_factory=list)
    warnings: List[Dict[str, Any]] = field(default_factory=list)
    ambiguities: List[Dict[str, str]] = field(default_factory=list)

    def add_error(self, stage: str, message: str, detail: str = "") -> None:
        self.errors.append({"stage": stage, "message": message, "detail": detail})
        logger.error("TKB [%s] ERROR: %s%s", stage, message, f" — {detail}" if detail else "")

    def add_warning(self, stage: str, message: str, detail: str = "") -> None:
        self.warnings.append({"stage": stage, "message": message, "detail": detail})
        logger.warning("TKB [%s] WARNING: %s%s", stage, message, f" — {detail}" if detail else "")

    def add_ambiguity(self, spec_reference: str, description: str) -> None:
        self.ambiguities.append({"spec_reference": spec_reference, "description": description})
        logger.warning(
            "TKB ARCHITECTURAL AMBIGUITY in %r: %s — documented, not redesigned.",
            spec_reference, description,
        )

    @property
    def has_errors(self) -> bool:
        return len(self.errors) > 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "error_count": len(self.errors),
            "warning_count": len(self.warnings),
            "ambiguity_count": len(self.ambiguities),
            "errors": self.errors,
            "warnings": self.warnings,
            "ambiguities": self.ambiguities,
        }


class TKBContext:
    """Shared mutable build context passed through all TKB pipeline stages.

    IMMUTABLE after construction:
      - compiler_artifacts (dict of loaded upstream artifacts)
      - metadata (TKBMetadata — artifact_id, schema_version, etc.)
      - compiler_information (TKBCompilerInformation)
      - config (build configuration flags)

    MUTABLE during pipeline execution (written by builders):
      - outputs (the assembled sub-artifacts, keyed by stage name)
      - diagnostics (accumulated warnings/errors/ambiguities)
      - stage_timings (wall-clock duration per stage, for statistics)
    """

    def __init__(
        self,
        compiler_artifacts: Dict[str, Any],
        metadata: TKBMetadata,
        compiler_information: TKBCompilerInformation,
        config: Optional[Dict[str, Any]] = None,
    ) -> None:
        # Immutable inputs
        self._compiler_artifacts = compiler_artifacts
        self._metadata = metadata
        self._compiler_information = compiler_information
        self._config: Dict[str, Any] = config or {}

        # Mutable pipeline outputs
        self._outputs: Dict[str, Any] = {}
        self._diagnostics = TKBDiagnostics()
        self._stage_timings: Dict[str, float] = {}
        self._completed_stages: List[str] = []

    # -- Read-only properties -----------------------------------------------

    @property
    def compiler_artifacts(self) -> Dict[str, Any]:
        return self._compiler_artifacts

    @property
    def metadata(self) -> TKBMetadata:
        return self._metadata

    @property
    def compiler_information(self) -> TKBCompilerInformation:
        return self._compiler_information

    @property
    def artifact_id(self) -> str:
        return self._metadata.artifact_id

    @property
    def config(self) -> Dict[str, Any]:
        return self._config

    @property
    def diagnostics(self) -> TKBDiagnostics:
        return self._diagnostics

    # -- Stage output management --------------------------------------------

    def set_output(self, stage: str, output: Any) -> None:
        """Called by a builder stage to record its output. Idempotent —
        a stage that re-runs (e.g. after error recovery) simply overwrites
        its previous output."""
        self._outputs[stage] = output
        if stage not in self._completed_stages:
            self._completed_stages.append(stage)
        logger.debug("TKBContext: stage %r output recorded.", stage)

    def get_output(self, stage: str) -> Optional[Any]:
        """Returns the output of a previously completed stage, or None
        if that stage has not yet run or produced no output."""
        return self._outputs.get(stage)

    def require_output(self, stage: str, requesting_stage: str) -> Any:
        """Like get_output but raises TKBBuilderError if the stage output
        is absent — used by stages with hard dependencies."""
        from .exceptions import TKBBuilderError
        output = self._outputs.get(stage)
        if output is None:
            raise TKBBuilderError(
                requesting_stage,
                f"required output from stage {stage!r} is not available. "
                f"Ensure stages run in correct pipeline order.",
            )
        return output

    @property
    def completed_stages(self) -> List[str]:
        return list(self._completed_stages)

    @property
    def outputs(self) -> Dict[str, Any]:
        """Read-only view of all accumulated outputs (for serialization)."""
        return dict(self._outputs)

    # -- Timing tracking ----------------------------------------------------

    def record_stage_timing(self, stage: str, elapsed_seconds: float) -> None:
        self._stage_timings[stage] = round(elapsed_seconds, 4)

    @property
    def stage_timings(self) -> Dict[str, float]:
        return dict(self._stage_timings)

    # -- Configuration helpers ----------------------------------------------

    def get_config(self, key: str, default: Any = None) -> Any:
        return self._config.get(key, default)

    def is_strict_validation(self) -> bool:
        """True if validation should be strict (fail on warnings). Default False."""
        return bool(self._config.get("strict_validation", False))

    def is_determinism_enforced(self) -> bool:
        """True if determinism checks are enforced. Default True."""
        return bool(self._config.get("enforce_determinism", True))
